"use client"

import type { ImportMappingConfig } from "@/types/firestore-models"

import { createEmptyMappingEntry } from "./import-mapping-types"

export function createDefaultImportMappingConfig(): ImportMappingConfig {
  return {
    id: "standard-mapping",
    name: "標準マッピング",
    description: "標準の受注ファイル形式に対応する初期設定です。",
    startDetailRow: 17,
    validRowColumn: "R",
    active: true,
    deleted: false,
    version: 1,
    customerRule: "ALL",
    entries: [
      createEmptyMappingEntry({
        id: "default-a",
        targetColumns: ["A"],
        targetColumnName: "会社コード",
        dataSource: "orderFile",
        orderFileMode: "fixedCell",
        sourceCell: "K4",
        scope: "sheet",
      }),
      createEmptyMappingEntry({
        id: "default-eij",
        targetColumns: ["E", "I", "J"],
        targetColumnName: "得意先コード",
        dataSource: "orderFile",
        orderFileMode: "fixedCell",
        sourceCell: "D4",
        scope: "sheet",
      }),
      createEmptyMappingEntry({
        id: "default-k",
        targetColumns: ["K"],
        targetColumnName: "納入先コード",
        dataSource: "orderFile",
        orderFileMode: "fixedCell",
        sourceCell: "K8",
        scope: "sheet",
      }),
      createEmptyMappingEntry({
        id: "default-w",
        targetColumns: ["W"],
        targetColumnName: "受注日",
        dataSource: "orderFile",
        orderFileMode: "fixedCell",
        sourceCell: "Q5",
        format: "date",
        scope: "sheet",
      }),
      createEmptyMappingEntry({
        id: "default-xao",
        targetColumns: ["X", "AO"],
        targetColumnName: "出荷予定日",
        dataSource: "orderFile",
        orderFileMode: "sourceFormula",
        sourceDataKind: "number",
        sourcePosition: "Q7",
        sourceFormula: "Q7 - 1",
        format: "date",
        scope: "sheet",
      }),
      createEmptyMappingEntry({
        id: "default-y",
        targetColumns: ["Y"],
        targetColumnName: "出荷予定日",
        dataSource: "orderFile",
        orderFileMode: "fixedCell",
        sourceCell: "Q7",
        format: "date",
        scope: "sheet",
      }),
      createEmptyMappingEntry({
        id: "default-ad",
        targetColumns: ["AD"],
        targetColumnName: "売上伝票行番号",
        dataSource: "formula",
        formula: "=ROW_NUMBER",
        scope: "system",
      }),
      createEmptyMappingEntry({
        id: "default-z",
        targetColumns: ["Z"],
        targetColumnName: "拡張コード項目２",
        dataSource: "orderFile",
        orderFileMode: "detailColumn",
        sourceColumn: "C",
        startRow: 17,
        endDetectionColumn: "R",
        scope: "detail",
      }),
      createEmptyMappingEntry({
        id: "default-aa",
        targetColumns: ["AA"],
        targetColumnName: "拡張コード項目３",
        dataSource: "orderFile",
        orderFileMode: "detailColumn",
        sourceColumn: "I",
        startRow: 17,
        endDetectionColumn: "R",
        scope: "detail",
      }),
      createEmptyMappingEntry({
        id: "default-ab",
        targetColumns: ["AB"],
        targetColumnName: "拡張テキスト項目１",
        dataSource: "orderFile",
        orderFileMode: "detailColumn",
        sourceColumn: "E",
        startRow: 17,
        endDetectionColumn: "R",
        scope: "detail",
      }),
      createEmptyMappingEntry({
        id: "default-ag",
        targetColumns: ["AG"],
        targetColumnName: "商品名",
        dataSource: "orderFile",
        orderFileMode: "detailColumn",
        sourceColumn: "M",
        startRow: 17,
        endDetectionColumn: "R",
        scope: "detail",
      }),
      createEmptyMappingEntry({
        id: "default-ai",
        targetColumns: ["AI"],
        targetColumnName: "受注数",
        dataSource: "orderFile",
        orderFileMode: "detailColumn",
        sourceColumn: "R",
        startRow: 17,
        endDetectionColumn: "R",
        format: "number",
        scope: "detail",
      }),
      createEmptyMappingEntry({
        id: "default-am",
        targetColumns: ["AM"],
        targetColumnName: "取引通貨受注単価",
        dataSource: "orderFile",
        orderFileMode: "detailColumn",
        sourceColumn: "U",
        startRow: 17,
        endDetectionColumn: "R",
        format: "number",
        scope: "detail",
      }),
      createEmptyMappingEntry({
        id: "default-an",
        targetColumns: ["AN"],
        targetColumnName: "取引通貨明細受注金額",
        dataSource: "orderFile",
        orderFileMode: "detailColumn",
        sourceColumn: "V",
        startRow: 17,
        endDetectionColumn: "R",
        format: "number",
        scope: "detail",
      }),
      createEmptyMappingEntry({
        id: "default-ap",
        targetColumns: ["AP"],
        targetColumnName: "ベトナム工場の資材コード",
        dataSource: "orderFile",
        orderFileMode: "detailColumn",
        sourceColumn: "L",
        startRow: 17,
        endDetectionColumn: "R",
        scope: "detail",
      }),
      createEmptyMappingEntry({
        id: "default-aq",
        targetColumns: ["AQ"],
        targetColumnName: "単位コード(工場)",
        dataSource: "orderFile",
        orderFileMode: "detailColumn",
        sourceColumn: "S",
        startRow: 17,
        endDetectionColumn: "R",
        scope: "detail",
      }),
    ],
  }
}
